AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FitMentor - Modular Serverless Stack in Tel Aviv (il-central-1) (API
  Gateway + Lambda + DynamoDB + Cognito)
Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
    - x86_64
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME:
          Ref: FitMentorTableName
Parameters:
  StageName:
    Type: String
    Default: prod
  ResetUrlBase:
    Type: String
    Default: ''
  FitMentorTableName:
    Type: String
    Default: FitMentorData
  AdminEmail:
    Type: String
    Default: admin@example.com
  GoogleApiKey1:
    Type: String
    Default: ''
    NoEcho: true
  GoogleApiKey2:
    Type: String
    Default: ''
    NoEcho: true
  GoogleApiKey3:
    Type: String
    Default: ''
    NoEcho: true
  LabRoleArn:
    Type: String
    Description: IAM Role ARN to use for all Lambdas (Optional)
    Default: ''
Conditions:
  HasLabRoleArn:
    Fn::Not:
    - Fn::Equals:
      - Ref: LabRoleArn
      - ''
Resources:
  FitMentorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: FitMentorTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: UserID
        AttributeType: S
      - AttributeName: DataType
        AttributeType: S
      KeySchema:
      - AttributeName: UserID
        KeyType: HASH
      - AttributeName: DataType
        KeyType: RANGE
  FitMentorLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: FitMentorBackendAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            Resource:
              Fn::GetAtt:
              - FitMentorTable
              - Arn
          - Effect: Allow
            Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminUserGlobalSignOut
            - cognito-idp:AdminEnableUser
            - cognito-idp:AdminDisableUser
            - cognito-idp:AdminAddUserToGroup
            - cognito-idp:AdminListGroupsForUser
            - cognito-idp:ListUsersInGroup
            - cognito-idp:ListUsers
            - cognito-idp:SignUp
            - cognito-idp:ConfirmSignUp
            - cognito-idp:ForgotPassword
            - cognito-idp:ConfirmForgotPassword
            - cognito-idp:ResendConfirmationCode
            Resource: '*'
  FitMentorCognitoCustomMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FitMentorCognitoCustomMessage
      CodeUri: s3://fitmentor-deployments-835922063181-il/6cee30ba7ee053ece6914f6b1695d9f0
      Handler: index.handler
      Role:
        Fn::If:
        - HasLabRoleArn
        - Ref: LabRoleArn
        - Fn::GetAtt:
          - FitMentorLambdaExecutionRole
          - Arn
      Environment:
        Variables:
          RESET_URL_BASE:
            Ref: ResetUrlBase
  FitMentorUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FitMentorUserPool
      AutoVerifiedAttributes:
      - email
      UsernameAttributes:
      - email
      LambdaConfig:
        CustomMessage:
          Fn::GetAtt:
          - FitMentorCognitoCustomMessageFunction
          - Arn
      Schema:
      - Name: email
        Required: true
        Mutable: true
      - Name: name
        Required: false
        Mutable: true
  CognitoInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: FitMentorCognitoCustomMessageFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - FitMentorUserPool
        - Arn
  FitMentorUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: FitMentorUserPool
      ClientName: FitMentorAppClient
      GenerateSecret: false
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_USER_SRP_AUTH
  FitMentorAdminsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Admins
      UserPoolId:
        Ref: FitMentorUserPool
      Description: Administrators group
  FitMentorUsersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Users
      UserPoolId:
        Ref: FitMentorUserPool
      Description: Regular users group
  FitMentorApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FitMentorApi
      StageName:
        Ref: StageName
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
  FitMentorLogicFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FitMentorLogic
      CodeUri: s3://fitmentor-deployments-835922063181-il/c7bea7e81581123b4d3132c95bc4ff73
      Handler: index.handler
      Role:
        Fn::If:
        - HasLabRoleArn
        - Ref: LabRoleArn
        - Fn::GetAtt:
          - FitMentorLambdaExecutionRole
          - Arn
      Environment:
        Variables:
          COGNITO_USER_POOL_ID:
            Ref: FitMentorUserPool
          COGNITO_CLIENT_ID:
            Ref: FitMentorUserPoolClient
          ADMIN_EMAIL:
            Ref: AdminEmail
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId:
              Ref: FitMentorApi
            Path: /API
            Method: POST
  FitMentorDashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FitMentorDashboard
      CodeUri: s3://fitmentor-deployments-835922063181-il/a97d889740ea8101a31a2bdb11a8bf07
      Handler: index.handler
      Role:
        Fn::If:
        - HasLabRoleArn
        - Ref: LabRoleArn
        - Fn::GetAtt:
          - FitMentorLambdaExecutionRole
          - Arn
      Environment:
        Variables:
          GOOGLE_API_KEY1:
            Ref: GoogleApiKey1
          GOOGLE_API_KEY2:
            Ref: GoogleApiKey2
          GOOGLE_API_KEY3:
            Ref: GoogleApiKey3
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId:
              Ref: FitMentorApi
            Path: /Dashboard
            Method: POST
  FitMentorProgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FitMentorProgress
      CodeUri: s3://fitmentor-deployments-835922063181-il/8f6b628325d966345387a110b3d4294e
      Handler: index.handler
      Role:
        Fn::If:
        - HasLabRoleArn
        - Ref: LabRoleArn
        - Fn::GetAtt:
          - FitMentorLambdaExecutionRole
          - Arn
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId:
              Ref: FitMentorApi
            Path: /Progress
            Method: POST
  FitMentorTrainingLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FitMentorTrainingLog
      CodeUri: s3://fitmentor-deployments-835922063181-il/f970b4a9a2a0c55f9f9b9ff22f59a2f3
      Handler: index.handler
      Role:
        Fn::If:
        - HasLabRoleArn
        - Ref: LabRoleArn
        - Fn::GetAtt:
          - FitMentorLambdaExecutionRole
          - Arn
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId:
              Ref: FitMentorApi
            Path: /TrainingLog
            Method: POST
Outputs:
  ApiInvokeUrl:
    Description: Base Invoke URL for FitMentor API Gateway
    Value:
      Fn::Sub: https://${FitMentorApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  UserPoolId:
    Description: FitMentor Cognito User Pool ID
    Value:
      Ref: FitMentorUserPool
  UserPoolClientId:
    Description: FitMentor Cognito User Pool Client ID
    Value:
      Ref: FitMentorUserPoolClient
  DynamoDbTableName:
    Description: FitMentor Single DynamoDB Table Name
    Value:
      Ref: FitMentorTableName
